### ISSUE TITLE
Quoted Strings Parsed Incorrectly

### ISSUE THREAD

**Issue by daveismith** [dpjanes/iotdb-links#1]
RFC 6690 allows quoted strings to be used in link format text. These quoted strings must be used for strings that contain the semi-colons (;). An example is 

link-format text: </zcl>;ep="nih:sha-256;bob";if=urn:zcl:v0;rt=urn:zcl
parsed object: {"/zcl":{"ep":"\"nih:sha-256","bob\";if":"urn:zcl:v0","rt":"urn:zcl"}}

**Comment by dpjanes** [comment]
The parsed object you're referencing is what you're currently getting? And what the correct response should be is `{"/zcl":{"ep":"nih:sha-256;bob","if":"urn:zcl:v0","rt":"urn:zcl"}}`?

**Comment by daveismith** [comment]
Correct. I expect what you've put.

**Comment by dpjanes** [comment]
I just pushed a new version and published on npm. please confirm it works for you.

**Comment by daveismith** [comment]
Seems to have solved it.
